### ISSUE TITLE
Python 3 get_uri() secret byte string

### ISSUE THREAD

**Issue by sl2000** [steveherrin/SpookyOTP#1]
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32

from spookyotp import (get_random_secret, TOTP)
secret = get_random_secret(n_bytes=10)
totp = TOTP(secret, 'Example', 'user@example.org')
totp.get_uri()

Got: "otpauth://totp/Example:user%40example.org?secret=b'RSXGR72VK5UTXJDG'&issuer=Example&digits=6&algorithm=sha1&period=30"

Expected: "otpauth://totp/Example:user%40example.org?secret=RSXGR72VK5UTXJDG&issuer=Example&digits=6&algorithm=sha1&period=30"

Can resolve with
spookyotp\otp.py
101 -   encoded_secret = base64.b32encode(secret)
101 +   encoded_secret = base64.b32encode(secret).decode()

**Comment by steveherrin** [comment]
Thanks! I also fixed the test that was letting this slip past.

**Comment by sl2000** [comment]
Thank you for the library - it does exactly what I needed.

Simon
